server:
  port: 8888
  
spring:
  application:
    name: gateway-server-opd
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"    
      routes:
      - id: core-service
        uri: lb://CORE-SERVICE
        predicates:
          - Path=/**
        filters:
        - AuthFilter

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  token:
    secret: _7hCFHDLM8ae0GsE0rWeaE_8gFYrM33_Wf0hV6XHif-FWmb_V23nL6To6P3AJJIIruY6-Iwjzh_ZsnzZsbSfXQ
    validity: 864000000